# Generated by Django 4.2 on 2023-05-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('house_address', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('Organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organizations')),
            ],
        ),
    ]
