# Generated by Django 4.2 on 2023-05-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_organizations_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_organization',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_worker',
            field=models.BooleanField(null=True),
        ),
    ]
